//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFRCenterGlobal.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PFRCenterGlobal.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AboutApp {
            get {
                return ResourceManager.GetString("AboutApp", resourceCulture);
            }
        }
        
        public static string LabelInfoAbout {
            get {
                return ResourceManager.GetString("LabelInfoAbout", resourceCulture);
            }
        }
        
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        public static string SlideMenuMain {
            get {
                return ResourceManager.GetString("SlideMenuMain", resourceCulture);
            }
        }
        
        public static string SlideMenuAccount {
            get {
                return ResourceManager.GetString("SlideMenuAccount", resourceCulture);
            }
        }
        
        public static string SlideMenuExit {
            get {
                return ResourceManager.GetString("SlideMenuExit", resourceCulture);
            }
        }
        
        public static string SlideMenuAbout {
            get {
                return ResourceManager.GetString("SlideMenuAbout", resourceCulture);
            }
        }
        
        public static string BottomToolBtnHome {
            get {
                return ResourceManager.GetString("BottomToolBtnHome", resourceCulture);
            }
        }
        
        public static string BottomToolBtnEvents {
            get {
                return ResourceManager.GetString("BottomToolBtnEvents", resourceCulture);
            }
        }
        
        public static string BottomToolBtnCart {
            get {
                return ResourceManager.GetString("BottomToolBtnCart", resourceCulture);
            }
        }
        
        public static string BottomToolBtnSpecialists {
            get {
                return ResourceManager.GetString("BottomToolBtnSpecialists", resourceCulture);
            }
        }
        
        public static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }
        
        public static string TitleEvents {
            get {
                return ResourceManager.GetString("TitleEvents", resourceCulture);
            }
        }
        
        public static string TitleSpecialists {
            get {
                return ResourceManager.GetString("TitleSpecialists", resourceCulture);
            }
        }
        
        public static string TitleCart {
            get {
                return ResourceManager.GetString("TitleCart", resourceCulture);
            }
        }
        
        public static string TitleHello {
            get {
                return ResourceManager.GetString("TitleHello", resourceCulture);
            }

        }
        public static string TitleMap
        {
            get
            {
                return ResourceManager.GetString("TitleMap", resourceCulture);
            }
        }
    }
}
